### ISSUE TITLE
Missing packages in Ubuntu 16.04

### ISSUE THREAD

**Issue by fsuarez6** [davetcoleman/moveit_kinetic_cpp11#2]
To be able to build in Ubuntu 16.04, I had to add the following packages from source:
* `household_objects_database_msgs`
* `manipulation_msgs`

```{bash}
cd ~/ws_moveit/src
git clone https://github.com/ros-interactive-manipulation/household_objects_database_msgs
git clone https://github.com/ros-interactive-manipulation/manipulation_msgs
```

**Comment by davetcoleman** [comment]
Yes, this repo is now deprecated since we have the main repo working now. We already have that in the new rosinstall file:
https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit.rosinstall

I'll update this README to note this, sorry about that. Can you remind me what linked you to this repo?

**Comment by fsuarez6** [comment]
Having the main repo working now is great!
The last conment of [this issue](https://github.com/ros-planning/moveit_core/issues/313#issuecomment-235638214) links to this repo.

**Comment by davetcoleman** [comment]
Great! fyi I moved the instructions yet again today, to hopefully its final resting place on the moveit website: 
https://github.com/ros-planning/moveit.ros.org/pull/29/files
